### ISSUE TITLE
Doesn't actually work?

### ISSUE THREAD

**Issue by onionhammer** [AnteWall/react-cast-sender#1]
Hey - is this actually still working? Even just the sample docs page doesnt show the chromecast button

https://antewall.github.io/react-cast-sender/

**Comment by AnteWall** [comment]
It does work, however it's not 100% finished yet and therefor the docs are still using my developer receiverApplicationId and that one only allow to cast to my personal chromecast so it will never find any chromecast other then that one. 

But if you install the package and choose your own it should still work.

**Comment by onionhammer** [comment]
@AnteWall No, I changed the receiverApplicationId to be the default media receiver, and it still doesnt work. I hacked it a bit to modify this line:

https://github.com/AnteWall/react-cast-sender/blob/master/src/context/CastProvider.tsx#L67

to just

```js
    if (window.cast) {
```

and it worked

**Comment by onionhammer** [comment]
![image](https://user-images.githubusercontent.com/969938/59545087-33d59f80-8edf-11e9-8e09-6f72118ed993.png)
