### ISSUE TITLE
Toggling connected/disconnected doesnt always trigger re-render

### ISSUE THREAD

**Issue by onionhammer** [AnteWall/react-cast-sender#3]
When I toggle the cast button multiple times, with this code, I expect it to switch between the <chromecast player> and the <inline player>, but the useCast hook does not cause the `Player` component to re-render when the `connected` should be toggling between true and false

```js
const Player = (props: PlayerProps) => {
    const castProps = useCast();

    console.log("Rendering");

    return castProps.connected 
        ? <ChromecastPlayer {...props} />
        : <InlinePlayer {...props} />
};
```

**Comment by AnteWall** [comment]
It should be solved in `v0.1.7`
